// import '../../..styles/_globals.scss';
import { Inter } from 'next/font/google';
import NextHead from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Head() {
    return (
      <NextHead>
            <title>Crumb recipe app</title>
            <meta name="description"  content="Crumb recipe app"/>
            <meta name="keywords" content="Crumb recipe app"/>
      </NextHead>
    );
}
